# Generated by Django 4.1.5 on 2023-01-14 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
